added notification support

diff --git a/bg-changer b/bg-changer
--- a/bg-changer
+++ b/bg-changer
@@ -2,6 +2,12 @@
 
 curl -s "http://www.bing.com/HPImageArchive.aspx?mkt=en-US&format=xml&idx=0&n=1" -o /tmp/file.xml
 urlEnd=$(sed -n 's:.*<url>\(.*\)</url>.*:\1:p' /tmp/file.xml)
-curl "www.bing.com$urlEnd" -o /tmp/bg
+curl -s "www.bing.com$urlEnd" -o /tmp/bg
 gsettings set org.gnome.desktop.background picture-uri file:///tmp/bg
+if [ "$?" == 0 ];then
+	notify-send "title" "BG successfully updated" -i gtk-dialog-info
+else
+	notify-send "title" "error" -i error
+fi
 rm /tmp/file.xml
+
